### PR TITLE
[scwfparam] Allow to output any spectral values with ShakeMap >= 4

### PR DESCRIPTION
**Pull request by gempa-jabe**
Add configuration `wfparam.output.shakeMap.pgm` to define the spectral values exported to ShakeMap >= 4.

```
wfparam.output.shakeMap.pgm = pga, pgv, psa03, psa10, psa30
```

is the default.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
@luca-s you might want to check it before merging into master.

**Comment by luca-s** [comment]
@gempa-jabe LGTM unless you would like us to test it internally before merging

**Comment by gempa-jabe** [comment]
@luca-s if you have test cases where this particular feature change would apply then of course, please give it a try. I have tested the configuration and the output station XML file for ShakeMap where both were looking good.

**Comment by luca-s** [comment]
If you have already tested it then I will merge it. On our side we'll try the feature and if there are small fixes to be done then can be fixed on master.

**Pull request merged**
