### PR TITLE
NLL7 update

### PR DESCRIPTION
**Pull request by filefolder**
Hi, as suggested I am submitting a rough version of the NLL plugin updated to version 7.00.13 17Jan2022. 

I think there are still lots of improvements to be made; this was done quickly just to use the azimuthal_equidist projection for a local catalog. In particular there are many unused variables and probably a few functions left over from the original NLL code that aren't relevant for seiscomp. Otherwise, to the best of my knowledge everything works as expected. 

If it is of any use I am glad

### CODE REVIEW

**Comment by luca-s** [comment]
Thank you for this PR. We are certainly interested in updating the NLL code. Since the Swiss Seismological Service (SED) highly relies on NonLinLoc we will have to go through a a thorough testing phase before merging this PR. However this is something we want to do.

Could you tell me the commit you fetched the NonLinLoc code from? I would like to keep track of that for future updates.

**Comment by filefolder** [comment]
It was the one from Jan 20 2022, https://github.com/alomax/NonLinLoc/commit/c29a13ecdf10bef11c21d01262e87d0c47228321. There was a recent update a few days ago but I think this was mostly doc and sh files. 

Also small update to my previous post, I have found a bug with the plugin when using `TRANS_MERC`. For reasons I don't understand, solving a **second** time (e.g. first using the plugin to solve for a location, then clicking to doing it again) often causes the event's location to jump directly north (from negative latitude) nearly to the equator. I suspect the `north_pole` boolean value in the original map_project.c is not being handled properly.

**Comment by luca-s** [comment]
I reviewed this PR and I pulled the changes to a new branch called [NLLupdate](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/tree/NLLupdate).

I also integrated the latest commits from [NonLinLoc repo](https://github.com/alomax/NonLinLoc).

I have also cleaned up the commit history: there is a single commit with the import of the code from NLL "as is" and one single commit with the changes for SeisComP. The idea is to make straightforward to integrate further changes from NLL

@filefolder: while I found your clean up of the code very nice, I preferred to stick to the unmodified files from the original code, even though we don't need all that options in SeisComP.  This is in line with the idea of keep further integrations simple. I only kept the removal of JSON dependency.

I have also run some backward compatibility tests and it looks all good.

**Comment by luca-s** [comment]
@gempa-jabe I believe this PR should not go into SeisComP 5 and we should merge the change to master. In this way we can run several tests and by the time SeisComP 6 is out, the new NLL version will roll in automatically. What do you think?

**Comment by gempa-jabe** [comment]
It is fine with me. Although it would not break binary compatibility (it is an addon) there might be still unexpected behaviour and breaking that within one major version is not desired. I agree with testing and postponing it for the next major.

**Comment by luca-s** [comment]
Good, then I'll keep testing the [NLLupdate](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/tree/NLLupdate) branch for a while and when I am confident with it I will merge it to master.

**Comment by luca-s** [comment]
The [NLLupdate](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/tree/NLLupdate) branch is now merged into master branch.

**Pull request closed without merging**
